# Generated by Django 4.2.9 on 2025-11-01 02:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('QUOTA_WARNING', 'Quota Warning'), ('QUOTA_EXCEEDED', 'Quota Exceeded'), ('THREAT_DETECTED', 'Threat Detected'), ('ANOMALY_DETECTED', 'Anomaly Detected'), ('SERVICE_DOWN', 'Service Down'), ('HIGH_ERROR_RATE', 'High Error Rate')], max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('layout', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'dashboards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('granularity', models.CharField(choices=[('MINUTE', 'Per Minute'), ('HOUR', 'Per Hour'), ('DAY', 'Per Day')], max_length=20)),
                ('total_requests', models.BigIntegerField(default=0)),
                ('successful_requests', models.BigIntegerField(default=0)),
                ('failed_requests', models.BigIntegerField(default=0)),
                ('blocked_requests', models.BigIntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(default=0)),
                ('p95_response_time_ms', models.FloatField(default=0)),
                ('p99_response_time_ms', models.FloatField(default=0)),
                ('threat_count', models.IntegerField(default=0)),
                ('high_risk_requests', models.IntegerField(default=0)),
                ('unique_ips', models.IntegerField(default=0)),
                ('unique_endpoints', models.IntegerField(default=0)),
                ('bytes_sent', models.BigIntegerField(default=0)),
                ('bytes_received', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'metric_snapshots',
                'ordering': ['-timestamp'],
            },
        ),
    ]
