# Generated by Django 4.2.9 on 2025-11-01 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('applications', '0002_initial'),
        ('analytics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='applications.application'),
        ),
        migrations.AddField(
            model_name='alert',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='metricsnapshot',
            index=models.Index(fields=['application', 'granularity', '-timestamp'], name='metric_snap_applica_90c256_idx'),
        ),
        migrations.AddIndex(
            model_name='metricsnapshot',
            index=models.Index(fields=['environment', 'granularity', '-timestamp'], name='metric_snap_environ_410c86_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metricsnapshot',
            unique_together={('application', 'environment', 'timestamp', 'granularity')},
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['organization', 'is_resolved', '-created_at'], name='alerts_organiz_822fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', 'is_resolved', '-created_at'], name='alerts_severit_ada3f2_idx'),
        ),
    ]
