# Generated by Django 4.2.9 on 2025-11-01 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0003_initial'),
        ('organizations', '0002_initial'),
        ('traffic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='threatdetection',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_threats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratelimitrule',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limit_rules', to='applications.application'),
        ),
        migrations.AddField(
            model_name='blockedip',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_ip_records', to='applications.application'),
        ),
        migrations.AddField(
            model_name='blockedip',
            name='blocked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_ips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockedip',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_ips', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='apirequest',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_requests', to='applications.environment'),
        ),
        migrations.AddIndex(
            model_name='threatdetection',
            index=models.Index(fields=['environment', 'status', '-created_at'], name='threat_dete_environ_f83b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='threatdetection',
            index=models.Index(fields=['severity', 'status', '-created_at'], name='threat_dete_severit_1bad1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blockedip',
            unique_together={('organization', 'ip_address')},
        ),
        migrations.AddIndex(
            model_name='apirequest',
            index=models.Index(fields=['environment', '-timestamp'], name='api_request_environ_9b7751_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequest',
            index=models.Index(fields=['ip_address', '-timestamp'], name='api_request_ip_addr_7a941b_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequest',
            index=models.Index(fields=['threat_score', '-timestamp'], name='api_request_threat__e0b93c_idx'),
        ),
    ]
