# Generated by Django 4.2.9 on 2025-11-01 02:45

import applications.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.TextField()),
                ('path_pattern', models.TextField()),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('request_count', models.BigIntegerField(default=0)),
                ('error_count', models.BigIntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('risk_score', models.IntegerField(default=0)),
                ('security_issues', models.JSONField(blank=True, default=list)),
                ('query_params', models.JSONField(blank=True, default=list)),
                ('body_params', models.JSONField(blank=True, default=list)),
                ('headers', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'api_endpoints',
                'ordering': ['-request_count'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('api_key', models.CharField(db_index=True, default=applications.models.generate_api_key, max_length=255, unique=True)),
                ('base_url', models.URLField(max_length=500)),
                ('target_url', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_traffic_enabled', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True)),
                ('allocated_quota', models.BigIntegerField(default=100000)),
                ('used_quota', models.BigIntegerField(default=0)),
                ('rate_limit_per_minute', models.IntegerField(default=1000)),
                ('rate_limit_per_hour', models.IntegerField(default=10000)),
                ('rate_limit_per_day', models.IntegerField(default=100000)),
                ('blocked_ips', models.JSONField(blank=True, default=list)),
                ('allowed_ips', models.JSONField(blank=True, default=list)),
                ('blocked_countries', models.JSONField(blank=True, default=list)),
                ('allowed_countries', models.JSONField(blank=True, default=list)),
                ('custom_headers', models.JSONField(blank=True, default=dict)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('framework', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('environment_type', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production'), ('testing', 'Testing'), ('custom', 'Custom')], default='production', max_length=50)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True)),
                ('max_applications', models.IntegerField(default=10)),
                ('allocated_quota', models.BigIntegerField(default=1000000)),
                ('env_variables', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'environments',
                'ordering': ['environment_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuotaTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('from_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quota_transfers_out', to='applications.application')),
            ],
            options={
                'db_table': 'quota_transfers',
                'ordering': ['-created_at'],
            },
        ),
    ]
