# Generated by Django 4.2.9 on 2025-11-01 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('applications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotatransfer',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quota_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotatransfer',
            name='to_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_transfers_in', to='applications.application'),
        ),
        migrations.AddField(
            model_name='environment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='application',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applications.environment'),
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_endpoints', to='applications.application'),
        ),
        migrations.AlterUniqueTogether(
            name='environment',
            unique_together={('organization', 'slug')},
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['api_key'], name='application_api_key_0c804e_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['environment', 'is_active'], name='application_environ_6aa31c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('environment', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='apiendpoint',
            unique_together={('application', 'method', 'path_pattern')},
        ),
    ]
