# Generated by Django 4.2.9 on 2025-11-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='dns_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='dns_verification_token',
            field=models.CharField(blank=True, help_text='Token used for DNS TXT verification (_sentrix-verify.<domain>)', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='edge_hostname',
            field=models.CharField(blank=True, help_text='Assigned SENTRIX edge hostname (e.g., c-<id>.edge.sentrix.io)', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='protected_domain',
            field=models.CharField(blank=True, help_text='Customer domain protected via SENTRIX (e.g., api.x.com)', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='traffic_mode',
            field=models.CharField(choices=[('api_key', 'API Key Header'), ('dns', 'DNS / Host-based')], default='api_key', max_length=20),
        ),
    ]
