# Generated by Django 4.2.9 on 2025-11-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_add_dns_onboarding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='bypass_token',
            field=models.CharField(blank=True, help_text='Emergency bypass token (if SENTRIX down, origin accepts this in X-SENTRIX-Bypass header)', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='origin_signature_key',
            field=models.CharField(blank=True, help_text='Secret key for signing proxied requests (X-SENTRIX-Signature header)', max_length=255),
        ),
    ]
