# Generated by Django 4.2.9 on 2025-11-01 02:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anomaly_type', models.CharField(choices=[('VELOCITY', 'Velocity Anomaly'), ('SEQUENCE', 'Sequence Anomaly'), ('DATA', 'Data Anomaly'), ('AUTHENTICATION', 'Authentication Anomaly'), ('GEOGRAPHIC', 'Geographic Anomaly'), ('TIMING', 'Timing Anomaly'), ('BOLA', 'BOLA/IDOR Attack'), ('SCRAPING', 'Data Scraping'), ('ENUMERATION', 'Resource Enumeration')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('confidence_score', models.FloatField()),
                ('risk_score', models.FloatField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('indicators', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField()),
                ('endpoint', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('DETECTED', 'Detected'), ('INVESTIGATING', 'Investigating'), ('CONFIRMED', 'Confirmed Threat'), ('FALSE_POSITIVE', 'False Positive'), ('RESOLVED', 'Resolved')], default='DETECTED', max_length=20)),
                ('investigated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'security_anomaly_detection',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='APIBehaviorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('method', models.CharField(max_length=10)),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('full_path', models.TextField()),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('status_code', models.IntegerField()),
                ('response_time_ms', models.FloatField()),
                ('request_size_bytes', models.IntegerField(default=0)),
                ('response_size_bytes', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('geo_country', models.CharField(blank=True, max_length=2)),
                ('geo_city', models.CharField(blank=True, max_length=100)),
                ('auth_method', models.CharField(blank=True, max_length=50)),
                ('api_key_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'security_api_behavior_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BlockedEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('IP', 'IP Address'), ('USER', 'User'), ('API_KEY', 'API Key'), ('SESSION', 'Session ID')], max_length=20)),
                ('entity_value', models.CharField(db_index=True, max_length=255)),
                ('reason', models.TextField()),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('is_permanent', models.BooleanField(default=False)),
                ('unblocked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'security_blocked_entity',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('velocity_threshold_multiplier', models.FloatField(default=3.0)),
                ('anomaly_score_threshold', models.FloatField(default=0.75)),
                ('min_requests_for_baseline', models.IntegerField(default=100)),
                ('baseline_window_days', models.IntegerField(default=7)),
                ('auto_block_enabled', models.BooleanField(default=False)),
                ('auto_rate_limit_enabled', models.BooleanField(default=True)),
                ('block_duration_minutes', models.IntegerField(default=60)),
                ('alert_on_severity', models.JSONField(default=list)),
                ('alert_channels', models.JSONField(default=list)),
                ('model_update_frequency_minutes', models.IntegerField(default=15)),
                ('feature_importance_threshold', models.FloatField(default=0.05)),
                ('false_positive_tolerance', models.FloatField(default=0.01)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Security Configuration',
                'verbose_name_plural': 'Security Configuration',
                'db_table': 'security_configuration',
            },
        ),
        migrations.CreateModel(
            name='ThreatResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_taken', models.CharField(choices=[('LOG', 'Log Only'), ('ALERT', 'Alert Security Team'), ('RATE_LIMIT', 'Apply Rate Limiting'), ('THROTTLE', 'Throttle Requests'), ('CHALLENGE', 'Challenge with CAPTCHA'), ('BLOCK_TEMPORARY', 'Temporary Block'), ('BLOCK_PERMANENT', 'Permanent Block')], max_length=20)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('parameters', models.JSONField(default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by_system', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'security_threat_response',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBehaviorBaseline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('avg_requests_per_hour', models.FloatField(default=0)),
                ('avg_requests_per_day', models.FloatField(default=0)),
                ('avg_response_time_ms', models.FloatField(default=0)),
                ('std_response_time_ms', models.FloatField(default=0)),
                ('avg_request_size_bytes', models.FloatField(default=0)),
                ('avg_response_size_bytes', models.FloatField(default=0)),
                ('common_endpoints', models.JSONField(default=list)),
                ('common_user_agents', models.JSONField(default=list)),
                ('common_countries', models.JSONField(default=list)),
                ('typical_hours', models.JSONField(default=list)),
                ('typical_sequences', models.JSONField(default=list)),
                ('samples_count', models.IntegerField(default=0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('baseline_window_days', models.IntegerField(default=7)),
            ],
            options={
                'db_table': 'security_user_behavior_baseline',
            },
        ),
    ]
