# Generated by Django 4.2.9 on 2025-11-01 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userbehaviorbaseline',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threatresponse',
            name='anomaly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.anomalydetection'),
        ),
        migrations.AddField(
            model_name='securityconfiguration',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockedentity',
            name='anomaly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.anomalydetection'),
        ),
        migrations.AddField(
            model_name='blockedentity',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockedentity',
            name='unblocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unblocked_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apibehaviorlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anomalydetection',
            name='behavior_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='security.apibehaviorlog'),
        ),
        migrations.AddField(
            model_name='anomalydetection',
            name='investigated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigated_anomalies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anomalydetection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userbehaviorbaseline',
            index=models.Index(fields=['user', 'last_calculated'], name='security_us_user_id_56f950_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbehaviorbaseline',
            unique_together={('user', 'endpoint')},
        ),
        migrations.AddIndex(
            model_name='blockedentity',
            index=models.Index(fields=['entity_type', 'entity_value', 'blocked_until'], name='security_bl_entity__b109c7_idx'),
        ),
        migrations.AddIndex(
            model_name='apibehaviorlog',
            index=models.Index(fields=['user', 'timestamp'], name='security_ap_user_id_8ff830_idx'),
        ),
        migrations.AddIndex(
            model_name='apibehaviorlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='security_ap_ip_addr_97b236_idx'),
        ),
        migrations.AddIndex(
            model_name='apibehaviorlog',
            index=models.Index(fields=['endpoint', 'timestamp'], name='security_ap_endpoin_240456_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalydetection',
            index=models.Index(fields=['severity', 'status', 'timestamp'], name='security_an_severit_056140_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalydetection',
            index=models.Index(fields=['user', 'timestamp'], name='security_an_user_id_e1a558_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalydetection',
            index=models.Index(fields=['anomaly_type', 'timestamp'], name='security_an_anomaly_ddcd86_idx'),
        ),
    ]
