# Generated by Django 4.2.9 on 2025-11-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='annual_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=16.67, help_text='Discount percentage for annual billing (e.g., 16.67 = 2 months free). Set to 0 to disable.', max_digits=5),
        ),
    ]
